// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Infrastructure.Data;

#nullable disable

namespace TMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS.Domain.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("TMS.Domain.Entities.TicketComments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ticket_id")
                        .HasColumnType("int");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ticket_id");

                    b.HasIndex("User_id");

                    b.ToTable("TicketComments", (string)null);
                });

            modelBuilder.Entity("TMS.Domain.Entities.TicketStatusLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Changed_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Changed_By")
                        .HasColumnType("int");

                    b.Property<int>("New_Status")
                        .HasColumnType("int");

                    b.Property<int>("Old_Status")
                        .HasColumnType("int");

                    b.Property<int>("Ticket_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Changed_By");

                    b.HasIndex("Ticket_id");

                    b.ToTable("TicketStatusLogs", (string)null);
                });

            modelBuilder.Entity("TMS.Domain.Entities.Tickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assigned_To")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_By")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("Assigned_To");

                    b.HasIndex("Created_By");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("TMS.Domain.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("Role_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role_Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TMS.Domain.Entities.TicketComments", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Tickets", "Tickets")
                        .WithMany()
                        .HasForeignKey("Ticket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS.Domain.Entities.Users", "Users")
                        .WithMany("TicketComments")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Tickets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TMS.Domain.Entities.TicketStatusLogs", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Users", "Users")
                        .WithMany("TicketStatusLogs")
                        .HasForeignKey("Changed_By")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.Domain.Entities.Tickets", "Tickets")
                        .WithMany()
                        .HasForeignKey("Ticket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tickets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Tickets", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Users", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("Assigned_To")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TMS.Domain.Entities.Users", "CreatedByUser")
                        .WithMany("Tickets")
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Users", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Users", b =>
                {
                    b.Navigation("TicketComments");

                    b.Navigation("TicketStatusLogs");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
